# Generated by Django 5.1.7 on 2025-04-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
